### ISSUE TITLE
How to run this app in a single build and run once  

### ISSUE THREAD

**Issue by vijayakumarrajug** [PascalRomb/angular-microfrontend#1]
Please help me , how to run and build once. could you pls help how to implement.

**Comment by PascalRomb** [comment]
This is not the point of the app: some "part of the app" maybe are not running when mainPage (main App) is up.

You can run the main App without plugins and every single plugin can run on different machine.
it make no sense to run all over one machine, it will not be microfrontend anymore.

BUT if you want to test the app you can read README and make all steps. 
If you're searching for a faster solution you can copy/paste readme commands and make your own script.

write a .sh file with all commands with '&&' between commands and maybe it will works (with some adjustements). 
if you're on windows  system you can write a .bat file.
